### PR TITLE
Crag's dubbing

### PR DESCRIPTION
**Pull request by Fabrice-TIERCELIN**
Hi @misiokles,

This PR translates the _CRAG Hack_'s campaign speeches. It also fixes some typos.

- AI: https://huggingface.co/spaces/coqui/xtts
- CRAG Hack's voice: https://www.youtube.com/watch?v=2TuceYCDW3g#t=11m57

### CODE REVIEW

**Comment by Fabrice-TIERCELIN** [comment]
@misiokles, @heroesiiifan, are there _WOG_ campaigns? How to start an _HOTA_ campaign?

**Comment by misiokles** [comment]
WoG maps and campaigns are not supported. 
For Hota campaigns - just download from launcher campaigns pack mod

**Comment by Olegmods** [comment]
> @misiokles, @heroesiiifan, are there _WOG_ campaigns? How to start an _HOTA_ campaign?

HotA campaigns don't work correctly IIRC. You can put it to the maps folder and start it as a custom campaign though.

WoG maps support was disabled long ago, so WoG campaigns aren't supported.

**Comment by Olegmods** [comment]
Plus Forged in Fire campaign is not supported too.

**Pull request merged**
